version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-49on6yu0123k"
s3_prefix = "sam-hello"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
